### ISSUE TITLE
Unable to create lead

### ISSUE THREAD

**Issue by sjaingupta** [sjaingupta/SalesforceTesting-Project_NYC#1]
Unable to create lead

**Steps to reproduce**

- Login to Salesforce application
- Open new lead page
- Enter the lead fields
- Save the lead

Expected Result:
Lead should be created successfully

Actual Result
Error message "Fax is mandatory" is displayed.
![image](https://user-images.githubusercontent.com/37231044/37237091-d45fb4ee-23d4-11e8-8ffc-acfbfea1f09a.png)

**Comment by pranavonline** [comment]
Issue is fixed

**Comment by sjaingupta** [comment]
Validated and closed the defect.

**Comment by sjaingupta** [comment]
Reopening the defect as issue is occurring again.

**Comment by pranavonline** [comment]
Defect is Non - reproducible.

**Comment by sjaingupta** [comment]
It seems to be test data issue. 
Working fine with correct data.
Closing this defect.
